import type { GoldenPathConfigRules } from "@workspace/db";

export type AgentRole = "architect" | "backend" | "frontend" | "security";

export interface AgentDefinition {
  role: AgentRole;
  label: string;
  buildPrompt: (config: GoldenPathConfigRules, context: AgentContext) => string;
  maxTokens: number;
}

export interface AgentContext {
  prompt: string;
  spec?: {
    overview: string;
    fileStructure: string[];
    apiEndpoints: Array<{ method: string; path: string; description: string }>;
    databaseTables: Array<{ name: string; columns: string[] }>;
    middleware: string[];
    architecturalDecisions: string[];
  };
  priorOutputs: Record<string, AgentOutput>;
}

export interface AgentOutput {
  role: AgentRole;
  files: Array<{ path: string; content: string }>;
  notes: string;
}

export interface AgentStageStatus {
  role: AgentRole;
  label: string;
  status: "pending" | "running" | "completed" | "failed";
  startedAt?: string;
  completedAt?: string;
  fileCount?: number;
  filePaths?: string[];
  notes?: string;
  error?: string;
}

function buildArchitectPrompt(config: GoldenPathConfigRules, ctx: AgentContext): string {
  const { techStack, folderStructure } = config;
  return `### ROLE
You are the **Architect Agent** for a multi-agent code generation pipeline. You design the application skeleton: project configuration, shared types, database schema, and entry points.

### YOUR RESPONSIBILITY
Generate ONLY these categories of files:
- package.json files (root, server, client)
- TypeScript configuration (tsconfig.json)
- Shared type definitions (types/ directory)
- Database schema files (server/src/schema/)
- Main entry points (server/src/index.ts, client/src/main.tsx)
- Environment configuration (.env.example)

### TECH STACK
- Backend: ${techStack.backend}
- Frontend: ${techStack.frontend}
- Language: ${techStack.language}
- ORM: ${techStack.orm}
- Validation: ${techStack.validation}

### FOLDER STRUCTURE
- Backend: ${folderStructure.backend.join(", ")}
- Frontend: ${folderStructure.frontend.join(", ")}
- Shared: ${folderStructure.shared.join(", ")}
- Root: ${folderStructure.root.join(", ")}

### OUTPUT FORMAT
Return a JSON object: { "files": [{ "path": "...", "content": "..." }], "notes": "Brief summary of architectural decisions" }
Do NOT include any text before or after the JSON.

### SPEC
${ctx.spec ? `Overview: ${ctx.spec.overview}\nFiles: ${ctx.spec.fileStructure.join(", ")}\nEndpoints: ${ctx.spec.apiEndpoints.map(e => `${e.method} ${e.path}`).join(", ")}\nTables: ${ctx.spec.databaseTables.map(t => t.name).join(", ")}\nMiddleware: ${ctx.spec.middleware.join(", ")}` : "No spec provided — design the architecture from the prompt."}`;
}

function buildBackendPrompt(config: GoldenPathConfigRules, ctx: AgentContext): string {
  const { techStack, security, database, errorHandling } = config;
  const architectOutput = ctx.priorOutputs["architect"];
  const architectNotes = architectOutput?.notes || "";
  const architectFiles = architectOutput?.files.map(f => f.path).join(", ") || "none";

  const securityRules: string[] = [];
  if (security.requireHelmet) securityRules.push("Use helmet for security headers");
  if (security.requireCors) securityRules.push("CORS with process.env.CLIENT_URL");
  if (security.requireRateLimiting) securityRules.push("Rate limiting on API endpoints");
  if (security.noHardcodedSecrets) securityRules.push("NO hardcoded secrets — use process.env for ALL sensitive values");

  return `### ROLE
You are the **Backend Developer Agent**. You implement the server-side code: API routes, middleware, business logic, and database operations.

### YOUR RESPONSIBILITY
Generate ONLY backend files:
- server/src/routes/ (API route handlers)
- server/src/middleware/ (auth, validation, error handling)
- server/src/lib/ (business logic, utilities)
- server/src/schema/ (only if Architect didn't provide them)

Do NOT generate frontend files, package.json, or config files (the Architect handles those).

### TECH STACK
- Backend: ${techStack.backend}, ORM: ${techStack.orm}, Validation: ${techStack.validation}

### RULES
- Every route MUST use ${techStack.validation} for input validation
- ${securityRules.join("; ")}
- ${database.requireParameterizedQueries ? "Parameterized queries only" : ""}
- ${errorHandling.requireGlobalHandler ? "Global error handler middleware" : ""}
- ${errorHandling.structuredResponses ? "Structured error responses" : ""}
- ${errorHandling.noStackTraceLeaks ? "No stack traces in responses" : ""}
- Complete, functional code — no stubs or TODOs

### ARCHITECT'S DECISIONS
${architectNotes}
Files already generated by Architect: ${architectFiles}

### OUTPUT FORMAT
Return a JSON object: { "files": [{ "path": "...", "content": "..." }], "notes": "Brief summary" }
Do NOT include any text before or after the JSON.

### SPEC
${ctx.spec ? `Endpoints: ${ctx.spec.apiEndpoints.map(e => `${e.method} ${e.path} — ${e.description}`).join("\n")}\nTables: ${ctx.spec.databaseTables.map(t => `${t.name}: ${t.columns.join(", ")}`).join("\n")}\nMiddleware: ${ctx.spec.middleware.join(", ")}` : ""}`;
}

function buildFrontendPrompt(config: GoldenPathConfigRules, ctx: AgentContext): string {
  const { techStack } = config;
  const architectOutput = ctx.priorOutputs["architect"];
  const backendOutput = ctx.priorOutputs["backend"];
  const architectNotes = architectOutput?.notes || "";
  const backendNotes = backendOutput?.notes || "";
  const backendRoutes = backendOutput?.files.filter(f => f.path.includes("routes/")).map(f => f.path).join(", ") || "none";

  return `### ROLE
You are the **Frontend Developer Agent**. You build the client-side UI: pages, components, hooks, styles, and API client.

### YOUR RESPONSIBILITY
Generate ONLY frontend files:
- client/src/components/ (React components)
- client/src/pages/ (page components)
- client/src/hooks/ (custom hooks, API integration)
- client/src/lib/ (utilities, API client)
- client/src/App.tsx (main app with routing)
- client/src/index.css (styles)

Do NOT generate backend files, package.json, or config files.

### TECH STACK
- Frontend: ${techStack.frontend}, Language: ${techStack.language}

### RULES
- Use React functional components with TypeScript
- Implement proper loading states, error handling, and empty states
- Use the API client to communicate with backend routes
- Responsive design with clean, modern UI
- Complete, functional code — no stubs or TODOs

### CONTEXT FROM PRIOR AGENTS
Architect notes: ${architectNotes}
Backend notes: ${backendNotes}
Backend routes available: ${backendRoutes}

### OUTPUT FORMAT
Return a JSON object: { "files": [{ "path": "...", "content": "..." }], "notes": "Brief summary" }
Do NOT include any text before or after the JSON.

### SPEC
${ctx.spec ? `Overview: ${ctx.spec.overview}\nEndpoints to consume: ${ctx.spec.apiEndpoints.map(e => `${e.method} ${e.path} — ${e.description}`).join("\n")}` : ""}`;
}

function buildSecurityPrompt(_config: GoldenPathConfigRules, ctx: AgentContext): string {
  const allFiles: Array<{ path: string; content: string }> = [];
  for (const output of Object.values(ctx.priorOutputs)) {
    allFiles.push(...output.files);
  }
  const fileList = allFiles.map(f => f.path).join("\n");
  const codeSnippets = allFiles
    .filter(f => f.path.endsWith(".ts") || f.path.endsWith(".tsx"))
    .slice(0, 10)
    .map(f => `--- ${f.path} ---\n${f.content.slice(0, 500)}`)
    .join("\n\n");

  return `### ROLE
You are the **Security Reviewer Agent**. You review ALL generated code and produce hardened replacements for any files with security issues.

### YOUR RESPONSIBILITY
Review the generated codebase for:
1. Hardcoded secrets, passwords, API keys, or tokens
2. Missing input validation on API routes
3. Missing security headers (helmet)
4. Missing CORS configuration
5. Missing rate limiting
6. SQL injection vulnerabilities
7. XSS vulnerabilities in frontend code
8. Missing error handling that could leak stack traces
9. Missing authentication/authorization checks
10. Insecure dependencies or patterns

### INSTRUCTIONS
- If a file has security issues, output a REPLACEMENT version with the fixes applied
- If the codebase is secure, return an empty files array
- Include a "notes" field describing what you found and fixed
- Do NOT change functionality — only fix security issues

### FILES TO REVIEW
${fileList}

### CODE SAMPLES
${codeSnippets}

### OUTPUT FORMAT
Return a JSON object: { "files": [{ "path": "...", "content": "..." }], "notes": "Security review summary" }
Do NOT include any text before or after the JSON.`;
}

export const AGENTS: AgentDefinition[] = [
  {
    role: "architect",
    label: "Architect",
    buildPrompt: buildArchitectPrompt,
    maxTokens: 16384,
  },
  {
    role: "backend",
    label: "Backend Developer",
    buildPrompt: buildBackendPrompt,
    maxTokens: 32768,
  },
  {
    role: "frontend",
    label: "Frontend Developer",
    buildPrompt: buildFrontendPrompt,
    maxTokens: 32768,
  },
  {
    role: "security",
    label: "Security Reviewer",
    buildPrompt: buildSecurityPrompt,
    maxTokens: 16384,
  },
];
